polls/urls.py
from . import views
from django.conf.urls import include, url
from django.urls import include, path

urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('changepass/', views.MyPasswordChangeView.as_view(), name='changepass'),
    path('changepassdone/', views.MyPasswordChangeDoneView.as_view(), name='chnagepassdone'),
    path('dashboard/', views.MyDashboardView.as_view(), name='dashboard'),

    # Menu Urls
    path('manageMenu', views.ShowMenuListView.as_view(), name='manageMenu'),
    path('createMenu', views.CreateMenuView.as_view(), name='createMenu'),
    path('editMenu/<str:slug>', views.MenuUpdateView.as_view(), name='editMenu'),
    path('deleteMenu/<str:slug>', views.DeleteMenuView.as_view(), name='deleteMenu'),
    path('createOrder', views.CreateOrderView.as_view(), name='createOrder'),
    path('manageOrder', views.ManageOrderView.as_view(), name='manageOrder'),
    path('showOrder', views.ShowOrderListView.as_view(), name='show'),
    path('orderPrint', views.ShowOrderPrintView.as_view(), name='orderPrint'),

    # Bills Url
    path('viewBills', views.ShowBillsListView.as_view(), name='viewBills'),
    path(r'^viewOrder/(?P<invoice_no>\d+)$', views.ViewOrderListView.as_view(), name='viewOrder'),
    path('viewOrderDetails', views.ViewOrderDetialsView.as_view(), name='viewOrderDetails'),
    path(r'^dateWiseDetials/(?P<pk>\d+)$', views.ViewDateWiseOrderDetialsView.as_view(), name='dateWiseDetials'),
    path('orderReportPDF/<int:pk>', views.ViewOrderPDFReportView.as_view(), name='orderReportPDF'),
    path('orderReportCSV/<int:pk>', views.ViewOrderCSVReportView.as_view(), name='orderReportCSV'),
    path('receiptBill/<int:invoice_no>', views.ViewRecieptBillView.as_view(), name='receiptBill'),

    # Data visualization url
    path('barCharts', views.ViewBarVisualizationView.as_view(), name='barCharts'),
    path('lineCharts', views.ViewLineVisualizationView.as_view(), name='lineCharts'),
    path('pieCharts', views.ViewPieVisualizationView.as_view() ,name='pieCharts'),
    path('api/chart/data', views.ChartData.as_view()),

    # Filter data visualization
    path('barChartsFilter', views.ViewBarChartsFilterView.as_view(), name='barChartsFilter'),
    path('lineChartsFilter', views.ViewLineChartsFilterView.as_view(), name='lineChartsFilter'),
    path('pieChartsFilter', views.ViewPieChartFilterView.as_view(), name='pieChartsFilter'),
    path('api/chart/filterdata', views.ChartDataFilter.as_view()),

    # Raw material url
    path('manageRawMaterial', views.ViewManageRawMaterialView.as_view(), name='manageRawMaterial'), 
    path('createRawMaterial', views.ViewCreateRawMaterialView.as_view(), name='createRawMaterial'), 
    path('editRawMaterial/<str:slug>', views.ViewRawMaterialUpdateView.as_view(), name='editRawMaterial'),  
    path('deleteRawmaterial/<int:pk>', views.ViewRawMaterialDeleteView.as_view(), name='deleteRawmaterial'),

    # Stock url
    path('manageStock', views.ViewRawmaterialStockView.as_view(), name='manageStock'),
    path('addStock', views.ViewCreatreStockView.as_view(), name='addStock'),
    path(r'^stockDetials/(?P<stock_item_id>\d+)$', views.ViewStockDetilasView.as_view(), name='stockDetials'),
    path(r'^useStock/(?P<pk>\d+)$', views.ViewStockUseView.as_view(), name='useStock'),
    path(r'^stockUse/(?P<stock_item_id>\d+)$', views.ViewStockUseDetialsView.as_view(), name='stockUse'),
    path('purchaseStock', views.ViewPurchaseStockView.as_view(), name='purchaseStock'),
    path('StockReport', views.ViewPurchaseStockReportView.as_view(), name='StockReport'),
    path('useStock', views.ViewUseStockView.as_view(), name='useStock'),
    path('useStockReport', views.ViewUseStockReportView.as_view(), name='useStockReport'),

    # ManageExpenses url
    path('manageExpenses', views.ViewManageExpenses.as_view(), name='manageExpenses'),
    path('createExpeses', views.ViewCreateNewExpeses.as_view(), name='createExpeses'),
    path(r'^editexpeses/(?P<pk>\d+)$', views.ViewExpesesUpdateView.as_view(), name='editexpeses'),
    path(r'^deleteexpeses/(?P<pk>\d+)$', views.ViewExpesesDeleteView.as_view(), name='deleteexpeses'),

    # manage paid expeses url
    path('paidExpeses', views.ViewPaidExpesesView.as_view(), name='paidExpeses'),
    path('addExpeses', views.ViewCreateNewExpeses.as_view(), name='addExpeses'),
    path('paidExpesesReport', views.ViewPaidExpesesReportView.as_view(), name='paidExpesesReport'),
    path('expensesreport', views.ViewExpesesReportView.as_view(), name='expensesreport'),  
    path('incomeAndGains', views.ViewIncomeAndgains.as_view(), name='incomeAndGains'),
    path('expensesAndGainsReport', views.ViewExpeseAndGainsReport.as_view(), name='expensesAndGainsReport'),
    
]


restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

polls/models.py
from __future__ import unicode_literals
from django.db import models
from .slugs import *
from django.db.models.signals import pre_save


# Add farmer model
class Menu(models.Model):
	menu_name = models.CharField(max_length=50, null=True)
	status = models.IntegerField(default=1,null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	slug = models.SlugField(unique=True, null=True, blank=True)

	def __str__(self):
		return self.menu_name	

	class Meta:
		db_table = "Menu"

def pre_save_menu(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator_menuname(instance)

pre_save.connect(pre_save_menu, sender = Menu)

# Invoice Model
class Invoice(models.Model):
	invoice_no = models.IntegerField(null=True)
	invoice_item_quantity = models.FloatField(null=True)
	invoice_item_final_total = models.FloatField(null=True)
	invoice_date = models.DateField()
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateTimeField(auto_now_add=True, null=True)
	updated_at = models.DateTimeField(auto_now=True, null=True)

	class Meta:
		db_table = "Invoice"

# Orders Model
class Orders(models.Model):
	invoice_no = models.IntegerField(null=True)
	item_name = models.ForeignKey(Menu, on_delete=models.CASCADE, null=True)
	item_price = models.FloatField(null=True)
	item_qty = models.FloatField(null=True, default=0)
	item_total = models.FloatField(null=True)
	item_date = models.DateField()
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)


	def __int__(self):
		return "%d"(self.id	)

	class Meta:
		db_table = "Orders"
	

# Ordersmaster Model
class OrdersMaster(models.Model):
	master_date = models.DateField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __int__(self):
		return "%d"(self.id)

	class Meta:
		db_table = "OrdersMaster"


class RawMaterialItem(models.Model):
	raw_item = models.CharField(max_length=50, null=True)
	status = models.IntegerField(default=1,null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	slug = models.SlugField(unique=True, null=True, blank=True)

	def __str__(self):
		return self.raw_item
		

	class Meta:
		db_table = "RawMaterialItem"

def pre_save_rawmaterial(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator_rawitem(instance)

pre_save.connect(pre_save_rawmaterial, sender = RawMaterialItem)


class AddStockTmp(models.Model):
	stock_item = models.ForeignKey(RawMaterialItem,  on_delete=models.CASCADE, null=True)
	stock_kg_qty = models.FloatField(null=True)
	price = models.FloatField(null=True)
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

	def __str__(self):
		return self.stock_item
	

class AddStockMaster(models.Model):
	stock_item = models.ForeignKey(RawMaterialItem,  on_delete=models.CASCADE, null=True)
	stock_kg_qty = models.FloatField(null=True)
	price = models.FloatField(null=True)
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)
	

class UseStock(models.Model):
	stock_item = models.ForeignKey(RawMaterialItem, on_delete=models.CASCADE, null=True)
	use_kg_qty = models.FloatField(null=True)
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateField(auto_now_add=True)
	updated_at = models.DateField(auto_now=True)

	class Meta:
		db_table = "UseStock"


# Report list model (create manunal report type)
class ReportList(models.Model):
	name = models.CharField(max_length=200, null=True)
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	class Meta:
		db_table = "ReportList"	

class StockReport(models.Model):
	stock_item = models.ForeignKey(RawMaterialItem,  on_delete=models.CASCADE, null=True)
	list_name = models.ForeignKey(ReportList, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

	class Meta:
		db_table = 	"StockReport"


class ExpesesList(models.Model):
	expenses_name = models.CharField(max_length=200, null=True)
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.expenses_name

	class Meta:
		db_table = 	"ExpesesList"

class ExpensesMaster(models.Model):
	expenses = models.ForeignKey(ExpesesList,  on_delete=models.CASCADE, null=True)
	expenses_amount = models.FloatField(null=True)
	desc = models.CharField(max_length=300, null=True)
	status = models.IntegerField(default=1, null=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.expenses

	class Meta:
		db_table = 	"ExpensesMaster"

polls/templates/add_raw_material.html
{% extends 'header.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>ERP Admin</title>
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/errors.css' %}" rel="stylesheet">
 
</head>
<body>
  <div class="container-fluid">
	  <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add New Raw Material</h6>
      </div>
        <div class="card-body">
          <div class="col-lg-12">
            <div class="card-body mx-auto shadow mb-4" style="max-width: 600px;">
               <h1 class="h5 text-gray-900 text-center">Add Raw Material Item</h1>
               <hr>
              <form method="post" action="{% url 'createRawMaterial' %}" autocomplete="off" novalidate>
                {% csrf_token %}
                <div class="form-group">                 
                 {% for field in form.visible_fields %}
                  <div class="form-group">                 
                    <label for="id_{{ field.name }}" class="control-label">
                      {{ field.label }}</label>
                    <div class="mb-2">{{ field }}</div>
                     {% if field.errors %}{{ field.errors }}{% endif %}
                  </div>
                {% endfor %}
                 {% for hidden in form.hidden_fields %}
                      {{ hidden }}
                  {% endfor %}
                </div> 
                <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>         
              </form>
              </div>             
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
	</div>
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% endblock %}
  </body>
</html>
 



 

polls/templates/changepass.html
{% extends 'header.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>FruitSuppliers</title>
            
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
          
          <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
          
        <style>
         input[type=password] {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #6e707e;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #d1d3e2;
    border-radius: .35rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
        </style>
        </head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                      <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-3"></div>
                  <div class="col-lg-6">
                    <div class="p-5">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Chanage Password</h1>
                      </div>
                    
                      <form action="" method="POST" novalidate>
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="Save" class="btn btn-primary btn-block"/>
                      </form>
                      <a href="{% url 'dashboard' %}">Cancel</a>
                        <hr>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>
{% endblock %}

polls/templates/changepassdone.html
{% extends 'header.html' %}
{% block body %}
{% load static %}
<html>
      <title>FruitSuppliers</title>
           <head>
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
          
          <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
      </head> 
      <body class="bg-light">
        <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        
        <a class="navbar-brand text-white">Password change successfully</a>  
      </nav>
      <span class="nav-link active">
        <a  href="{% url 'dashboard' %}">Back Dashboard</a>
      </span>  
      </div>
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>
{% endblock %}

polls/templates/dashboard.html
{% extends 'header.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/other.css' %}" rel="stylesheet">

</head>
<body>
	<body id="page-top">

		<!-- Page Wrapper -->
		<div id="wrapper">
	  
		 
		  <div id="content-wrapper" class="d-flex flex-column">
	  
			<!-- Main Content -->
			<div id="content">
			  <div class="container-fluid">
				<div class="row mt-4">
					<div class="col-xl-3 col-md-6 mb-4">
						<div class="card border-left-primary shadow h-100 py-2">
						  <div class="card-body">
							<div class="row no-gutters align-items-center">
							  <div class="col mr-2">
								<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Today)</div>
								<div class="h5 mb-0 font-weight-bold text-gray-800"><i class="fas fa-rupee-sign"></i>&nbsp;
									{% if earn_list.item_total__sum > 0 %}
										{{earn_list.item_total__sum}}
									{% else %}
										0
									{% endif %}		
								</div>
							  </div>
							  <div class="col-auto">
								<i class="fas fa-calendar fa-2x text-gray-300"></i>
							  </div>
							</div>
						  </div>
						</div>
					  </div>

					<div class="col-xl-3 col-md-6 mb-4">
						<div class="card border-left-primary shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Orders(Today)</div>
								<div class="h5 mb-0 font-weight-bold text-gray-800">{{order_list}}</div>
							</div>
							<div class="col-auto">
								<i class="fa fa-first-order  fa-2x text-gray-300"></i>
							</div>
							</div>
						</div>
						</div>
					</div>
					<div class="col-xl-3 col-md-6 mb-4">
						<div class="card border-left-primary shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Restaurant Menu</div>
								<div class="h5 mb-0 font-weight-bold text-gray-800">{{menu_list}}</div>
							</div>
							<div class="col-auto">
								<i class="fa fa-cutlery fa-2x text-gray-300"></i>
							</div>
							</div>
						</div>
						</div>
					</div>

					<div class="col-xl-3 col-md-6 mb-4">
						<div class="card border-left-primary shadow h-100 py-2">
						<div class="card-body">
							<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Stock Item</div>
								<div class="h5 mb-0 font-weight-bold text-gray-800">{{raw_item_list}}</div>
							</div>
							<div class="col-auto">
								<i class="fas fa-calendar fa-2x text-gray-300"></i>
							</div>
							</div>
						</div>
						</div>
					</div>
				</div>

				<div class="row mt-4">
					<div class="col-xl-3 col-md-6 mb-4">
						<div class="card border-left-primary shadow h-100 py-2">
						  <div class="card-body">
							<div class="row no-gutters align-items-center">
							  <div class="col mr-2">
								<div class="h5 mb-0 font-weight-bold text-gray-800">
									<a class="nav-link" href="{% url 'manageOrder' %}">
										<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
											<i class="fas fa-rupee-sign"></i>&nbsp; New Bill
										</div>
									</a>
								</div>
							  </div>
							  <div class="col-auto">
								<i class="fas fa-calendar fa-2x text-gray-300"></i>
							  </div>
							</div>
						  </div>
						</div>
					  </div>
				</div>

				<div class="d-sm-flex align-items-center justify-content-between mt-2 mb-2">
					<h5 class="text-danger font-weight-bold">Today Sale Item</h5>  
				  </div>

				<div class="row">
	  				{% for item, qty in order_data %}
		    			<div class="col-xl-3 col-md-6 mb-4">			 
							<div class="card border-left-success shadow h-100 py-2">					 	
						 		<div class="card-body">
						   			<div class="row no-gutters align-items-center">
										<div class="col mr-2">
							   				<div class="text-xl font-weight-bold text-uppercase mb-1" style="color :#D2386C">{{item}}</div>
											
											{% if qty.item_qty__sum > 100 %}   
							   					<div class="mb-0 font-weight-bold text-success blink_sale_item">QTY - <span class="h5 font-weight-bold">{{qty.item_qty__sum}}</span></div>
											{% else %}	
												<div class="mb-0 font-weight-bold text-danger">QTY - <span class="h5 font-weight-bold">{{qty.item_qty__sum}}</span></div>
											{% endif %}	
											
							 			</div>
										<div class="col-auto">
											<i class="fas fa-plus fa-2x text-gray-300 mb-0"></i>
										</div>
						   			</div>
						 		</div>
								 								
					   		</div>							  					
						</div>
					{% endfor %}   
				</div>	
				 
				<!-- Page Heading -->
				<div class="d-sm-flex align-items-center justify-content-between mt-2 mb-2">
				  <h5 class="text-danger font-weight-bold">Remaining Stock</h5>

				</div>
	  
				<!-- Content Row -->
				<div class="row">
	  
				 {% for i in stock_list %}
				  <div class="col-xl-3 col-md-6 mb-4">
					{% if i.stock_kg_qty > 100 %} 
						<div class="card border-left-success shadow h-100 py-2">
					{% else %}
						<div class="card border-left-danger shadow h-100 py-2">	
					{% endif %}			
					  <div class="card-body">
						<div class="row no-gutters align-items-center">
						  <div class="col mr-2">
							<div class="text-xl font-weight-bold text-uppercase mb-1" style="color :#D2386C">{{i.stock_item}}</div>
							{% if i.stock_kg_qty > 100 %}
							<div class="mb-0 font-weight-bold text-success">QTY / KG - <span class="h5 font-weight-bold">{{i.stock_kg_qty}}</span></div>
							{% endif %}

							{% if i.stock_kg_qty <= 100 %}
							<div class="mb-0 font-weight-bold text-danger blink">QTY / KG -<span class="h5 font-weight-bold">{{i.stock_kg_qty}}</span></div>
							{% endif %}

						  </div>
						  <div class="col-auto">
							<i class="fas fa-shopping-cart fa-2x text-gray-300"></i>
						  </div>
						</div>
					  </div>
					</div>					
				  </div>
				  {% endfor %}

				</div>	
			  </div>  
			</div>	
		  </div>		
		</div>
	
		<a class="scroll-to-top rounded" href="#page-top">
		  <i class="fas fa-angle-up"></i>
		</a>
	  
		<!-- Logout Modal-->
		<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
			<div class="modal-content">
			  <div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
				<button class="close" type="button" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">×</span>
				</button>
			  </div>
			  <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
			  <div class="modal-footer">
				<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
				<a class="btn btn-primary" href="login.html">Logout</a>
			  </div>
			</div>
		  </div>
		</div>	  
	  </body>
	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

	<script>
	function blink_text() {
		$('.blink').fadeOut(500);
		$('.blink').fadeIn(500);
	}
	setInterval(blink_text, 1000);

	function blink_sale_item() {
		$('.blink_sale_item').fadeOut(500);
		$('.blink_sale_item').fadeIn(500);
	}
	setInterval(blink_sale_item, 1000);
	</script>
</body>
</html>
{% endblock %}

polls/templates/date_wise_order_detials.html
{% extends 'header.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>ERP Admin</title>
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  
</head>
<body>
<!-- Begin Page Content -->
        <div class="container-fluid mt-4">
          <div class="card shadow mb-4">
            <div class="card-header">
            	
              {% for i in date_obj %}
                <a href="{% url 'orderReportPDF' i.id %}" class="btn btn-sm btn-danger float-right ml-2" target="_blank"><i class="fa fa-file-pdf mr-1"></i>PDF</a>
                <a href="{% url 'orderReportCSV' i.id %}" class="btn btn-sm btn-success float-right"><i class="fa fa-file-excel mr-1"></i>CSV</a>
              {% endfor %}
             

            

              <span class="font-weight-bold text-primary">Show Order</span>              
              {% for i in date_obj %}
                  <span class="font-weight-bold text-danger"><center>DATE : {{i.master_date}}</center></span>
              {% endfor %}        
            </div>           
            
             {% if messages %}
                    <span class="text-success font-weight-bold text-center mt-1">
                      {% for message in messages %}
                        {{ message }}
                      {% endfor %}
                    </span>
                  {% endif %}
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered"  width="100%" cellspacing="0">
                  <thead>
                    <tr class="text-center bg-secondary text-white">
                        <th scope="col">Sr No</th>
                        <th scope="col">Item Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr> 
                      {% for j in split_order %}                   
                      <td colspan="5" class="bg-light font-weight-bold text-center">Bill No : {{j.invoice_no}}</td>
                        {% for i in order_list %} 
                          {% if i.invoice_no == j.invoice_no %}                                    
                          <tr class="text-center font-weight-bold">
                            <td>{{forloop.counter}}</td>                            
                            <td>{{i.item_name | title}}</td>  
                            <td>{{i.item_price}}</td>   
                            <td>{{i.item_qty}}</td>  
                            <td>{{i.item_total}}</td>                  
                          </tr> 
                          {% endif %}                           
                        {% endfor %}  
                        <tr class="bg-light">
                          <td class="text-center font-weight-bold">Total</td>
                          <td colspan="2"></td>
                          <td class="text-center font-weight-bold">{{j.invoice_item_quantity}}</td>
                          <td class="text-center font-weight-bold">Rs. {{j.invoice_item_final_total}}</td>
                        </tr>                      
                    {% endfor %}     
                   
                  </tbody>
                </table>  
                <nav aria-label="Page navigation example">
                  {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                    {% endif %}

                    <li class="page-item active"><span class="page-link">{{page_obj.number}}</span></li>
                    
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                    {% endif %}
                  </ul>
                  {% endif %}
                </nav>                                
              </div>
            </div>
          </div>
</div>
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>
</html>

 



 